### PR TITLE
Add new RFC around shebang line best practices in hooks

### PR DESCRIPTION
**Pull request by christophermaier**
Signed-off-by: Christopher Maier <cmaier@chef.io>

### CODE REVIEW

**Comment by baumanj** [comment]
Is there any way we could provide better support around this?

`#!{{pkgPathFor "core/bash"}}/bin/bash` is awkward and breaks tooling (e.g., [`shellcheck`](https://www.shellcheck.net) that expects either of the two very standard variants:

1. `#!/bin/bash`
2.  `#!/usr/bin/env bash`

Maybe it's too magic-like, but I think it would be nice if the hooks could just use those directly and habitat did The Right Thing™.

**Comment by baumanj** [comment]
Great idea for an RFC, by the way. I'm 100% on board that this situation is dangerous and confusing and should be addressed.

**Comment by scotthain** [comment]
would `#!/usr/bin/env pkgPathFor core/bash` work? I think I've used that before...

**Comment by christophermaier** [comment]
@scotthain I don't think your `/usr/bin/env` line will work, since `pkgPathFor` is actually a custom Handlebars helper.

@baumanj Finding some way to use `env` would be interesting, but would probably take some work to accomplish (i.e., I think there's more work than just documenting something). 

I do like the explicitness of the `pkgPathFor` approach, even though it is admittedly verbose. It'd be nice if we had some template linting that could catch these kinds of scenarios at build time, too (e.g., you used `#!/bin/bash`, you used `pkgPathFor core/bash` without including that as a dependency, etc.)

**Comment by baumanj** [comment]
Yeah, I agree what I'm suggesting is actual feature work. I just thought now was the right time to consider if we *want* to do that work before going through the whole RFC process to document something else.

The answer may well be "no". It just seemed like the right point in time to consider it.

Either way, I'm 100% on board with this RFC once we answer that.

**Comment by christophermaier** [comment]
@rsertelon Yes, I think we should prefer `/bin/sh` when that's all that's really needed. It removes a runtime dependency at the very least 😄

**Comment by predominant** [comment]
Agreed on prefering `/bin/sh`

**Comment by johnjelinek** [comment]
k, so this has been approved for a while and no one has hit the button ... so I'm going to hit the button.

**Pull request merged**
